#!/usr/bin/env python3
# 2026-09-25T17:46:31+02:00 SHA-256:a7cfac2bea4602d60df97f08d492c18a67092c70a60e588b29a342aafb58d8f8

import argparse
import contextlib
import datetime
import hashlib
import json
import logging
import os
import random
import shutil
import stat
import string
import subprocess
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Generator, Self

logger = logging.getLogger(__name__)

whoami = "fetch"
env_prefix = f"{whoami.upper()}_"

def env(var, default=None) -> str | None:
    return os.environ.get(env_prefix + var, default)

def chmod_plus_x(path):
    umask = os.umask(0)
    os.umask(umask)
    os.chmod(path, os.stat(path).st_mode | ((stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) & ~umask))

def fresh_salt(n=5):
    alphabeth = string.ascii_letters + string.digits
    return ''.join(random.choices(alphabeth, k=n))

def figure_out_version():
    with open(__file__, "rb") as this:
        ls = this.readlines()
        shebang = ls[0]
        assert shebang.startswith(b"#!")

        h = hashlib.sha256()
        for l in ls[1:]:
            h.update(l)
        return h.hexdigest()

def parse_args():
    parser = argparse.ArgumentParser(
            description = "One script to fetch them all and in git bind them",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument("-v", "--version", action="version", version=figure_out_version())
    parser.add_argument("-q", "--quiet", action="store_true")

    parser.add_argument("--log", default=env("LOG_LEVEL", "WARN"), help="set log level")

    default_root = env("ROOT", ".")
    default_manifest_filename = env("MANIFEST_FILENAME", f".{whoami}.json")
    parser.add_argument("-R", "--root", metavar="ROOT", default=default_root, type=Path, help="act relative the directory ROOT")
    parser.add_argument("--manifest-filename", metavar="FILENAME", default=default_manifest_filename, type=Path, help="load manifest from FILENAME (relative to the ROOT)")
    parser.add_argument("-M", "--manifest", metavar="PATH", default=env("MANIFEST"), type=Path, help="load manifest from PATH")

    subparsers = parser.add_subparsers(dest="cmd")

    def add_timeout_arg(p):
        p.add_argument("-T", "--timeout", type=float)

    add_cmd = subparsers.add_parser("add")
    add_cmd.add_argument("-r", "--recursive", action="store_true", help="recurse into the fetched manifest")
    add_cmd.add_argument("-m", "--mkdir", action="store_true", help="mkdir necessary directories")
    add_cmd.add_argument("--sha256", metavar="SHA256")
    add_cmd.add_argument("url", metavar="URL")
    add_cmd.add_argument("target", metavar="TARGET", nargs="?")
    add_timeout_arg(add_cmd)

    verify_cmd = subparsers.add_parser("verify")
    verify_cmd.add_argument("target", metavar="TARGET", nargs="*")
    add_timeout_arg(verify_cmd)

    download_cmd = subparsers.add_parser("download")
    download_cmd.add_argument("-m", "--mkdir", action="store_true", help="mkdir necessary directories")
    download_cmd.add_argument("-u", "--update", action="store_true", help="redownload and update the manifest")
    download_cmd.add_argument("target", metavar="TARGET", nargs="*")
    add_timeout_arg(download_cmd)

    steal_this_script_cmd = subparsers.add_parser("steal-this-script")
    steal_this_script_cmd.add_argument("output", metavar="OUTPUT", nargs="?")

    subparsers.add_parser("ls")

    walk_cmd = subparsers.add_parser("walk")
    walk_cmd.add_argument("args", nargs="*")

    return parser.parse_args()

def setup_logger(level):
    l = logging.getLogger("fetch")
    l.setLevel(level)

    ch = logging.StreamHandler()
    ch.setLevel(level)

    f = logging.Formatter(fmt="%(asctime)s:%(name)s:%(levelname)s %(message)s", datefmt="%Y-%m-%dT%H:%M:%S%z")
    ch.setFormatter(f)

    l.addHandler(ch)

    return l

def download(url, target=None, timeout: float | None = None):
    m = hashlib.sha256()
    if target is None:
        logger.info("fetching: %s", url)
    else:
        logger.info("fetching: %s -> %s", url, target.name)

    ua = env("USER_AGENT", whoami)
    assert ua is not None
    req = urllib.request.Request(url, headers={
        "User-Agent": ua,
    })

    with urllib.request.urlopen(req, timeout=timeout) as f:
        while True:
            bs = f.read(4096)
            if len(bs) == 0:
                break
            logger.debug("fetching; %s: %s bytes", url, len(bs))
            m.update(bs)
            if target:
                target.write(bs)
    sha256 = m.hexdigest()
    logger.info("fetched; %s: SHA256 %s", url, sha256)
    return sha256

def sha256_file(path):
    with open(path, "rb") as f:
        m = hashlib.sha256()
        while True:
            bs = f.read(4096)
            if len(bs) == 0:
                break
            m.update(bs)
    return m.hexdigest()

@dataclass
class ChecksumMismatch(Exception):
    a: tuple[os.PathLike | str, str]
    b: tuple[os.PathLike | str, str]
    alg: str = "SHA256"

    def __str__(self):
        return repr(self)

Digest = str

@dataclass
class Item:
    url: str
    target: str
    timestamp: datetime.datetime
    sha256: Digest
    recurse: bool | None = None
    local: os.PathLike | None = None

    def __repr__(self):
        return f"Item({self.target}, {self.sha256})"

    def path(self, root: Path | None = None) -> Path:
        if isinstance(root, str):
            root = Path(root)
            # TODO: raise ValueError() and fix
        return (root or Path.cwd()) / self.target

    def exists(self, root=None):
        return os.path.exists(self.path(root))

    def download(self,
        root: Path | None = None,
        update: bool | None = None,
        timeout: float | None = None,
        mkdir: bool | None = None,
    ) -> Path:
        path = self.path(root)
        if update:
            self.timestamp = datetime.datetime.now().astimezone()
        os.makedirs(path.parent, exist_ok=True)
        self.local = path

        tmp = path.parent / f"{path.name}.{whoami}.{fresh_salt()}"
        try:
            with open(tmp, "xb") as f:
                fetched = download(self.url, f, timeout=timeout)

            if not update:
                if self.sha256 is not None and fetched != self.sha256:
                    raise ChecksumMismatch(a=(self.url, fetched), b=(f"{self}.sha256", self.sha256))

                if os.path.exists(path):
                    local = sha256_file(path)
                    if local != self.sha256:
                        raise ChecksumMismatch(a=(path, local), b=(f"{self}.sha256", self.sha256))

            self.sha256 = fetched
            if mkdir is True:
                path.parent.mkdir(parents=True, exist_ok=True)
            os.rename(tmp, path)
        finally:
            if os.path.exists(tmp):
                os.remove(tmp)

        return self.local

    @classmethod
    def new(cls,
        url: str,
        target: str,
        sha256: Digest | None,
        recurse: bool | None = None,
        **kwargs,
    ) -> tuple[Self, Path]:
        item = cls(
            url = url,
            target = target,
            timestamp = datetime.datetime.now().astimezone(),
            sha256 = sha256, # type: ignore
            recurse = recurse,
        )
        return item, item.download(**kwargs)

    def verify(self, root: Path | None = None, url=None, sha256=None) -> Path:
        if url is not None and self.url != url:
            raise RuntimeError("url doesn't match manifest", url, self.url)

        if sha256 is not None and self.sha256 != sha256:
            raise RuntimeError("sha256 doesn't match manifest", sha256, self.sha256)

        path = self.path(root)
        logger.info("verifying: %s", path)
        local = sha256_file(path)
        if local != self.sha256:
            raise ChecksumMismatch(a=(path, local), b=(f"{self}.sha256", self.sha256))
        self.local = path
        return self.local

    def to_dict(self):
        assert self.timestamp is not None
        d: dict[str, Any] = {
            "target": self.target,
            "url": self.url,
            "sha256": self.sha256,
            "timestamp": self.timestamp.isoformat(timespec="seconds"),
        }

        if self.recurse is True:
            d["recurse"] = True

        return d

    @classmethod
    def from_dict(cls, d) -> Self:
        return cls(
            target = d["target"],
            url = d["url"],
            sha256 = d["sha256"],
            timestamp = datetime.datetime.fromisoformat(d["timestamp"]),
            recurse = d.get("recurse"),
        )

@dataclass
class Manifest:
    path: Path
    items: dict[str, Item]

    @classmethod
    def load(cls, path):
        logger.debug("loading manifest: %s", path)

        with open(path, "rb") as f:
            js = json.load(f)

        items = {}
        for j in js:
            i = Item.from_dict(j)
            items[i.target] = i

        return cls(path, items)

    def __contains__(self, item) -> bool:
        if isinstance(item, Item):
            item = item.target
        return item in self.items

    def __getitem__(self, key) -> Item:
        if isinstance(key, Item):
            key = key.target
        return self.items[key]

    def get(self, key) -> Item | None:
        try:
            return self[key]
        except KeyError:
            return None

    def __iter__(self):
        yield from self.items.values()

    def add(self, item):
        if item.target in self.items:
            raise NotImplementedError()
        self.items[item.target] = item

    def to_dict(self):
        items = sorted(self, key=lambda i: i.target)
        items = map(lambda i: i.to_dict(), items)
        return list(items)

    def save(self):
        logger.debug("saving manifest: %s", self.path)
        with open(self.path, "w", encoding="UTF-8") as f:
            json.dump(self.to_dict(), f, sort_keys=True, indent=4)
            f.write("\n")

def resolve_root_and_manifest(args: argparse.Namespace, add=False) -> tuple[Path, Manifest]:
    root = args.root
    if root == ".":
        root = Path.cwd()
    logger.debug("root: %s", root)

    path = args.manifest
    if args.manifest is None:
        path = root / args.manifest_filename

    if add and not path.exists():
        return root, Manifest(path, {})

    return root, Manifest.load(path)

def choose_items(args: argparse.Namespace, manifest: Manifest) -> Generator[Item, None, None]:
    if vars(args).get("target"):
        for i in manifest:
            if i.target in args.target:
                yield i
    else:
        yield from manifest

def do_add(args):
    root, manifest = resolve_root_and_manifest(args, add=True)

    target = args.target
    if target is None:
        target = os.path.basename(args.url)

    target = os.path.relpath(os.path.join(root, target), start=root)

    item = manifest.get(target)
    if item is not None:
        if not item.exists(root=root):
            item.download(root=root, timeout=args.timeout, mkdir=args.mkdir)
        path = item.verify(url=args.url, sha256=args.sha256, root=root)
    else:
        item, path = Item.new(url=args.url, target=target, sha256=args.sha256, recurse=args.recursive, timeout=args.timeout, root=root, mkdir=args.mkdir)
        manifest.add(item)

    if not args.quiet:
        print(os.path.relpath(path, start=root))

    manifest.save()

def do_download(args):
    def go(root: Path, m: Manifest):
        for i in choose_items(args, m):
            path = i.download(root=root, update=args.update, timeout=args.timeout, mkdir=args.mkdir)

            if not args.quiet:
                print(os.path.relpath(path, start=root))

            if i.recurse:
                go(root, Manifest.load(path))
        if args.update:
            m.save()
    go(*resolve_root_and_manifest(args))

def do_verify(args):
    root, manifest = resolve_root_and_manifest(args)

    for i in choose_items(args, manifest):
        path = i.verify(root=root)
        if not args.quiet:
            print(os.path.relpath(path, start=root))

def do_steal_this_script(args):
    if args.output is None:
        dst = contextlib.nullcontext(sys.stdout.buffer)
    else:
        dst = open(args.output, "wb")

    with open(__file__, "rb") as src, dst as dst:
        ls = src.readlines()
        shebang = ls[0]
        assert shebang.startswith(b"#!")
        dst.write(shebang)

        h = hashlib.sha256()
        for l in ls[1:]:
            h.update(l)
        sha256 = h.hexdigest()

        now = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
        dst.write(f"# {now} SHA-256:{sha256}\n".encode("UTF-8"))

        for l in ls[1:]:
            dst.write(l)

    if args.output is not None:
        chmod_plus_x(args.output)

def do_list(args):
    root, manifest = resolve_root_and_manifest(args)

    for i in manifest:
        print(os.path.relpath(i.path(), start=root))

def walk(fn: str = whoami) -> Path | None:
    git = shutil.which("git")

    ps = [ Path.cwd() ]

    while ps:
        p = ps.pop()
        logger.debug("walking: %s", p)

        for f in [p / fn, p / "tools" / fn]:
            logger.debug("testing: %s", f)
            if f.is_file(follow_symlinks=True) and os.access(f, os.X_OK, follow_symlinks=True):
                return f

        if git is not None:
            try:
                [r] = subprocess.check_output([git, "-C", p, "rev-parse", "--show-toplevel"], text=True, stderr=subprocess.DEVNULL).splitlines()
                r = Path(r)
                if r != p:
                    ps.append(r)
                    continue
            except subprocess.CalledProcessError:
                pass

        r = p.parent
        if r != p:
            ps.append(r)

    p = shutil.which(fn)
    if p is not None:
        return Path(p)
    return None

def do_walk(args):
    p = walk()
    if p is None:
        logger.error("unable to find a fetch executable")
        sys.exit(1)

    if args == []:
        print(p)
    else:
        cmdline = [ p ] + args.args
        logger.debug("running: %s", cmdline)
        subprocess.check_call(cmdline)

def main():
    args = parse_args()
    global logger # pylint: disable=global-statement
    logger = setup_logger(args.log.upper())
    logger.debug("args: %s", args)

    if args.cmd == "add":
        do_add(args)
    elif args.cmd is None or args.cmd == "verify":
        do_verify(args)
    elif args.cmd == "download":
        do_download(args)
    elif args.cmd == "steal-this-script":
        do_steal_this_script(args)
    elif args.cmd == "ls":
        do_list(args)
    elif args.cmd == "walk":
        do_walk(args)
    else:
        raise RuntimeError(f"unexpected command: {args.cmd}")

if __name__ == "__main__":
    main()
